name: pubget
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  #firebase_auth: ^6.1.4
  #cloud_firestore: ^6.1.2
  #firebase_storage: ^13.0.6

  # State management
  #provider: ^6.1.5+1

  # UI and animations
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.12.0
  cached_network_image: ^3.4.1

  #images
  image_picker: ^1.2.1

  # In-app purchases
  in_app_purchase: ^3.2.3

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.3
  shared_preferences: ^2.5.4

  # Optional (swipe actions)
  flutter_slidable: ^4.0.3

  # Cupertino icons
  cupertino_icons: ^1.0.8

  #Api
  http: ^1.6.0
  #ad
  #google_mobile_ads: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


  flutter_native_splash: ^2.4.7



flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true
  ios: true




flutter:
  uses-material-design: true