name: pubget
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+18

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 4.9.0
  provider: ^6.1.5+1
  web: ^1.1.1
  firebase_auth: 6.5.1
  cloud_firestore: 6.4.1
  firebase_storage: 13.4.1
  google_sign_in: ^7.2.0
  image_picker: ^1.2.1
  cloud_functions: 6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true