name: pubget
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9

  # Firebase
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  firebase_storage: ^13.2.0
  google_sign_in: ^7.2.0

  # State Management
  provider: ^6.1.5+1

  # UI & Images
  cached_network_image: ^3.4.1
  image_picker: ^1.2.1
  flutter_svg: ^2.2.4
  google_fonts: ^8.0.2
  font_awesome_flutter: ^11.0.0
  flutter_staggered_animations: ^1.1.1

  # Networking & API
  http: ^1.6.0

  # Utils
  intl: ^0.20.2
  timeago: ^3.7.1
  shared_preferences: ^2.5.5
  uuid: ^4.5.3

  # Monetization
  google_mobile_ads: ^7.0.0

  in_app_purchase: ^3.2.3
  flutter_slidable: ^4.0.3
  async: ^2.13.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4


  flutter_native_splash: ^2.4.7



flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true
  ios: true




flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "true"
  image_path: "Assets1/images/Pubget_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "Assets1/images/Pubget_logo.png"